### ISSUE TITLE
Some text is black and hard to read

### ISSUE THREAD

**Issue by CGray1234** [NuggoDEV/Nuggo.tech#3]
In the "Projects" tab, there is some black text which is hard to read against the background
![Screenshot (109)](https://user-images.githubusercontent.com/102427011/204036156-77642079-46cc-44bd-b219-eafb35eb0a4f.jpg)

**Comment by NuggoDEV** [comment]
Ye Ik that happens I just cbf to update the website for that one thing, it'll be good to go on the next update for the repo which will hopefully fix scaling issues on this same page on mobile
